replicaCount: 1

image:
  repository: hslr/sun-panel

ingress:
  hostname: sunpanel.example.com
  https: false
  certificateName: wildcard-tls-certificate # only used for https mode

mysql:
  host: demo.namespace.svc
  username: root
  password: root
  port: 3306
  dbname: sun_panel

resources:
  limits:
    cpu: 20m
    memory: 60Mi
  requests:
    cpu: 10m
    memory: 30Mi
