apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "sun-panel.fullname" . }}
  labels:
    {{- include "sun-panel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: http
      protocol: TCP
      
  selector:
    {{- include "sun-panel.selectorLabels" . | nindent 4 }}
