apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sun-panel.fullname" . }}
  labels:
    {{- include "sun-panel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "sun-panel.fullname" . }}
  selector:
    matchLabels:
      {{- include "sun-panel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sun-panel.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/conf/conf.ini
              subPath: conf.ini
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: config
          configMap:
            name: {{ include "sun-panel.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: uploads
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

